### ISSUE TITLE
request for collaborator access

### ISSUE THREAD

**Issue by codedpratik** [Kuzma02/Fashion-eCommerce-Shop-in-React#1]
Hi sir,

I am currently working on the e commers website and need collaborator access to the repository to push my changes. Could you please grant me access?

Thank you!

Best regards,
shravaniloke

**Comment by Kuzma02** [comment]
Hi,

Thank you but this is one of my main portfolio projects and I don't want it to have any significant changes.

Best regards,
Aleksandar Kuzmanovic
